spring:
  datasource:
    url: jdbc:h2:~/graphqldb
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true